#!/usr/bin/env python

# Beah - Test harness. Part of Beaker project.
#
# Copyright (C) 2009 Marian Csontos <mcsontos@redhat.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

# IMPORT LIBRARY:
from beahlib import *

# CONFIGURE LIBRARY:
#def_conf(origin={"file":__file__, "module":__name__}, timestamp=True)
# DEMONSTRATE USING CALLABLE INSTEAD OF VALUE:
def_conf(origin=lambda x: {"file":__file__, "module":__name__}, timestamp=True)

# LOGGING:
linfo("Hello World!")
lwarning("IMO this is wrong...")
lerror("Finito!")

# LOSE DATA:
print "Some lose data."
from sys import stderr
print >> stderr, "And an error message."

# EXPLICITLY DEFINED LOSE DATA:
lose_item((["Intentionaly created loose item.",
    'Such an item can carry structured data.',
    'Only one argument - wrap in a tuple or a list.'], 1.23, {'1':'one'}))

# RESULTS:
passed(section="One.One")
passed(section="One")
failed(section="Two")
warning(section="Three")
failed()

