# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: beaker.spec

# add or remove files that should be synced
synced_files:
  - beaker.spec
  - .packit.yaml

notifications:
  pull_request:
    successful_build: false

jobs:
  - &copr_rhel_8_9
    job: copr_build
    trigger: pull_request
    targets:
      - epel-8-x86_64
      - epel-9-x86_64
    identifier: rhel_8_9

  - &copr_fedora
    job: copr_build
    trigger: pull_request
    targets:
      - fedora-all-x86_64
    identifier: fedora
    actions:
      post-upstream-clone:
        # disable broken unit tests
        - sed -i '/make check/d' beaker.spec

  - &copr_rhel_7
    job: copr_build
    trigger: pull_request
    targets:
      epel-7-x86_64:
        additional_repos:
          - https://beaker-project.org/yum/server/RedHatEnterpriseLinux7/
          - https://vault.centos.org/centos/7/extras/x86_64/
    identifier: rhel_7
    actions:
      post-upstream-clone:
        # Use gevent from base repositories during packit builds
        # gevent112 is our custom build with some backports to improve socket management
        - sed -i 's/python2-gevent112/python-gevent/g' beaker.spec
  - <<: *copr_rhel_8_9
    trigger: commit
    branch: python-3

  - <<: *copr_fedora
    trigger: commit
    branch: python-3

  - <<: *copr_rhel_7
    trigger: commit
    branch: python-3

