# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: beaker.spec

# add or remove files that should be synced
synced_files:
  - beaker.spec
  - .packit.yaml

notifications:
  pull_request:
    successful_build: false

jobs:
  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
        - epel-8-x86_64
        - epel-9-x86_64
        - centos-stream-8-x86_64
        - centos-stream-9-x86_64

  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
        - fedora-all-x86_64
    actions:
      post-upstream-clone:
        # disable broken unit tests
        - sed -i '/make check/d' beaker.spec
        # disable broken documentation
        - sed -i '/^make$/i sed -i s/documentation//g Makefile' beaker.spec
        - sed -i '/_mandir/d' beaker.spec
