linters:
  flake8:
    python: 3
    max-line-length: 120
    max-complexity: 20
  black:
    fixer: false
  csslint: {  }
  shellcheck:
    shell: bash
files:
  ignore:
    - 'bower_components/*'
    - 'node_modules/*'
