#!/bin/sh
set -e
if [ "$power_mode" == interrupt ] ; then
    echo "interrupt not supported by integrity" >&2
    exit 1
fi
fence_integrity -a "$power_address" -l "$power_user" -p "$power_pass" -o "$power_mode"
