#!/bin/bash
set -e
if [ "$power_mode" == interrupt ] ; then
    echo "interrupt not supported by lpar" >&2
    exit 1
fi
IFS=":" read -r power_sys power_lpar power_hmc <<<"$power_id"
fence_lpar -a "$power_address" -l "$power_user" -p "$power_pass" -H "$power_hmc" -x -s "$power_sys" -n "$power_lpar" -o "$power_mode"
