# License: GPL v2 or later
# Copyright Red Hat Inc. 2008

PKGNAME=beaker

.PHONY: all
all:	build

include ../rpmspec_rules.mk
include ../py_rules.mk

.PHONY: build
build:	py-build

.PHONY: install
install:	py-install

.PHONY: clean
clean:	py-clean
