#!/usr/bin/python

import sys, os
import xmlrpclib
from datetime import datetime
from datetime import timedelta
from cobbler import utils

if __name__ == '__main__':
    cobbler = xmlrpclib.ServerProxy('http://localhost/cobbler_api')
    token = cobbler.login("", utils.get_shared_secret())
    proxy = xmlrpclib.ServerProxy('http://localhost:8000', allow_none=True)
    distros = cobbler.get_distros()
    rdistros = []
    for distro in distros:
        if not os.path.exists(distro['kernel']):
            rdistros.append(distro['name'])
        elif len(sys.argv) > 1 and distro['name'].find(sys.argv[1]) != -1:
            rdistros.append(distro['name'])
    # if all distros are expired then something is probably wrong.
    if len(distros) != len(rdistros):
        for distro in rdistros:
            print "Removing distro %s" % distro
            cobbler.remove_distro(distro, token, True)
            proxy.removeDistro(distro)
    else:
        print "All distros are missing! Please check nfs mounts"
        sys.exit(1)
