#!/bin/bash
set -e

# Takes a random amount of time between 0-60 seconds,
# and randomly fails 1/10 times.

delay=$(($RANDOM % 60))
echo -n "dummy_flakey: sleeping for $delay seconds... "
sleep $delay
if [ $(($RANDOM % 10)) == 0 ] ; then
    echo "done, now failing"
    exit 1
fi
echo "done"
if [ "$power_mode" == "on" ] ; then
    curl -f -X PUT "http://localhost:8001/beah_dummy/$power_id"
fi
