#!/usr/bin/python

# Copyright (c) 2006 Red Hat, Inc. All rights reserved. This copyrighted material
 
# is made available to anyone wishing to use, modify, copy, or 
# redistribute it subject to the terms and conditions of the GNU General 
# Public License v.2.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
# Author: Bill Peck
#

import sys, getopt
import xmlrpclib

USAGE_TEXT = """
Usage: updateDistro -s http://lab_controller:8000 -d DISTRO -a ARCH
"""

def usage():
    print USAGE_TEXT
    sys.exit(-1)

def main():
    distro = None
    arch = None
    server = None
    args = sys.argv[1:]
    try:
        opts, args = getopt.getopt(args, 's:d:a:', 
                                        ['server=','distro=','arch='])
    except:
        usage()
    for opt, val in opts:
        if opt in ('-d', '--distro'):
            distro = val
        if opt in ('-a', '--arch'):
            arch = val
        if opt in ('-s', '--server'):
            server = val

    if distro and arch and server:
        session = xmlrpclib.ServerProxy(server)
        print session.updateDistro(distro,arch)
    else:
        usage()

if __name__ == '__main__':
    main()
    sys.exit(0)
