#!/bin/sh

# Source the common test script helpers
. /usr/bin/rhts_environment.sh

RESULT=FAIL

virsh capabilities | grep -q "<os_type>hvm</os_type>"
if [[ $? == 0 ]]; then
	RESULT=PASS
fi

report_result $TEST $RESULT

exit 0
