#!/bin/sh
#
# beah-srv:	Start the Beaker Harness server
#
# chkconfig:	345 99 99
# description:	The Beaker Harness server. Backend is required too...

# Source function library.
. /etc/rc.d/init.d/functions

# CUSTOMIZE THESE VARIABLES:

# NOTE: predefined functions (daemon, killproc, status) init.d/functions in
# el4 do not support -p/--pidfile options. pidfile has to be named same as
# binary file.
#
# In order to have multiple daemons of same type running at the same time it
# is necessary/recomended to create a wrapper with different name.
prog="beah-srv"
# FIXME: path should use the prefix used during installation, not the const
# /usr
BEAH_INSTALL_ROOT=/usr
# FIXME: this is not 100% reliable - if installed from egg these files are
# located in egg's tree.
export BEAH_ROOT=${BEAH_INSTALL_ROOT}/share/beah
export BEAHLIB_ROOT=$BEAH_ROOT
# FIXME: may need to change this(?)
RUN_AS=root

# DO NOT CHANGE THESE VARIABLES WITHOUT GOOD REASON:

path="$BEAH_INSTALL_ROOT/bin/$prog"
[ -f $path ] || exit 0
PIDFILE=/var/run/${prog}.pid
LOCKFILE=/var/lock/subsys/$prog

start() {
    echo -n $"Starting $prog: "
    daemon --user $RUN_AS $path ">> /tmp/$prog.out 2>&1 &" 'echo $!' ">$PIDFILE"
    RETVAL=$?
    #echo "\$!=$!"
    echo "$prog running as process `cat $PIDFILE`"
    echo
    if test $RETVAL = 0; then
        touch $LOCKFILE
    fi
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    if ! killproc $path; then
        kill `cat $PIDFILE`
    else
        true
    fi
    RETVAL=$?
    echo
    rm -f $LOCKFILE
    return $RETVAL
}

restart() {
    stop
    start
}

condrestart(){
	[ -e $LOCKFILE ] && restart
	return 0
}

# See how we were called.
case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    status)
	status $prog
	RETVAL=$?
        ;;
    restart)
	restart
	;;
    condrestart)
	condrestart
	;;
    reload)
        ;;
    *)
	echo $"Usage: $0 {start|stop|status|restart|condrestart|reload}"
	;;
esac
exit $RETVAL
