#!/bin/sh
set -e
if [ "$power_mode" == interrupt ] ; then
    echo "interrupt not supported by bullpap" >&2
    exit 1
fi
fence_bullpap -a "$power_address" -l "$power_user" -p "$power_pass" -d "$power_id" -o "$power_mode"
