#!/bin/sh
set -e
if [ "$power_mode" == interrupt ] ; then
    echo "interrupt not supported by wti" >&2
    exit 1
fi
fence_wti -v -a "$power_address" -n "$power_id" -p "$power_pass" -o "$power_mode"
